export type OrderState =
  | 'DRAFT'
  | 'QUOTE_REQUESTED'
  | 'QUOTE_LOCKED'
  | 'QUOTE_EXPIRED'
  | 'AWAITING_DEPOSIT'
  | 'DEPOSIT_DETECTED'
  | 'CONFIRMING'
  | 'DEPOSIT_CONFIRMED'
  | 'RISK_REVIEW'
  | 'COMPLIANCE_REVIEW'
  | 'ADDITIONAL_REVIEW_REQUIRED'
  | 'APPROVED_FOR_PAYOUT'
  | 'PAYOUT_PENDING'
  | 'PAYOUT_PROCESSING'
  | 'PAYOUT_COMPLETED'
  | 'PAYOUT_FAILED'
  | 'REJECTED'
  | 'CANCELLED'
  | 'EXPIRED'
  | 'RECOVERY_REQUIRED'
  | 'REFUNDED'
  | 'COMPLETED';

const ALLOWED_TRANSITIONS: Record<OrderState, OrderState[]> = {
  DRAFT: ['QUOTE_REQUESTED', 'CANCELLED', 'EXPIRED'],
  QUOTE_REQUESTED: ['QUOTE_LOCKED', 'QUOTE_EXPIRED', 'CANCELLED'],
  QUOTE_LOCKED: ['AWAITING_DEPOSIT', 'QUOTE_EXPIRED', 'CANCELLED'],
  QUOTE_EXPIRED: ['QUOTE_REQUESTED', 'CANCELLED'],
  AWAITING_DEPOSIT: ['DEPOSIT_DETECTED', 'EXPIRED', 'CANCELLED'],
  DEPOSIT_DETECTED: ['CONFIRMING', 'EXPIRED', 'RECOVERY_REQUIRED'],
  CONFIRMING: ['DEPOSIT_CONFIRMED', 'RECOVERY_REQUIRED'],
  DEPOSIT_CONFIRMED: ['RISK_REVIEW', 'APPROVED_FOR_PAYOUT', 'COMPLIANCE_REVIEW'],
  RISK_REVIEW: ['COMPLIANCE_REVIEW', 'APPROVED_FOR_PAYOUT', 'REJECTED', 'ADDITIONAL_REVIEW_REQUIRED'],
  COMPLIANCE_REVIEW: ['APPROVED_FOR_PAYOUT', 'REJECTED', 'ADDITIONAL_REVIEW_REQUIRED'],
  ADDITIONAL_REVIEW_REQUIRED: ['APPROVED_FOR_PAYOUT', 'REJECTED', 'REFUNDED'],
  APPROVED_FOR_PAYOUT: ['PAYOUT_PENDING', 'PAYOUT_PROCESSING', 'CANCELLED'],
  PAYOUT_PENDING: ['PAYOUT_PROCESSING', 'PAYOUT_FAILED', 'CANCELLED'],
  PAYOUT_PROCESSING: ['PAYOUT_COMPLETED', 'PAYOUT_FAILED'],
  PAYOUT_COMPLETED: ['COMPLETED'],
  PAYOUT_FAILED: ['PAYOUT_PENDING', 'RECOVERY_REQUIRED', 'REFUNDED'],
  REJECTED: [],
  CANCELLED: [],
  EXPIRED: [],
  RECOVERY_REQUIRED: ['REFUNDED', 'COMPLETED'],
  REFUNDED: [],
  COMPLETED: [],
};

export class OrderStateMachine {
  static canTransition(from: OrderState, to: OrderState): boolean {
    const allowed = ALLOWED_TRANSITIONS[from];
    return allowed ? allowed.includes(to) : false;
  }

  static validateTransition(from: OrderState, to: OrderState): void {
    if (!this.canTransition(from, to)) {
      throw new Error(`Invalid Order State Transition from '${from}' to '${to}'`);
    }
  }
}
